# Generated by Django 5.2.5 on 2026-08-25 06:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioClip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("2.0", "HSK 2.0 (ใช้อยู่ปัจจุบัน)"),
                            ("3.0", "HSK 3.0 (มาตรฐานใหม่)"),
                        ],
                        db_index=True,
                        default="2.0",
                        max_length=8,
                        verbose_name="มาตรฐาน",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            (
                                "official_past_paper",
                                "ข้อสอบเก่าทางการ (ลิขสิทธิ์ ห้ามขาย)",
                            ),
                            ("textbook", "หนังสือเตรียมสอบ (ลิขสิทธิ์ ห้ามขาย)"),
                            ("ai_generated", "สร้างด้วย AI"),
                            ("hand_written", "เขียนเอง"),
                            ("public_domain", "สาธารณสมบัติ"),
                        ],
                        db_index=True,
                        default="hand_written",
                        max_length=32,
                        verbose_name="ที่มา",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True,
                        help_text="เช่น H51001 หน้า 3 ข้อ 46",
                        max_length=200,
                        verbose_name="อ้างอิงที่มา",
                    ),
                ),
                (
                    "commercial_safe",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="ปิดเสมอสำหรับข้อสอบเก่าและเนื้อหาจากหนังสือ",
                        verbose_name="ใช้เชิงพาณิชย์ได้",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="ชื่อ")),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="audio/", verbose_name="ไฟล์เสียง"
                    ),
                ),
                (
                    "external_path",
                    models.CharField(
                        blank=True,
                        help_text="ใช้กับไฟล์ลิขสิทธิ์ที่ไม่ควรอัปโหลดเข้าระบบ ชี้ไปที่ไฟล์ในเครื่องแทน",
                        max_length=400,
                        verbose_name="พาธไฟล์ภายนอก",
                    ),
                ),
                (
                    "transcript_zh",
                    models.TextField(blank=True, verbose_name="บทถอดเสียง"),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ความยาว (มิลลิวินาที)"
                    ),
                ),
                (
                    "voice",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="เสียงที่ใช้"
                    ),
                ),
                ("speed", models.FloatField(default=1.0, verbose_name="ความเร็ว")),
            ],
            options={
                "verbose_name": "ไฟล์เสียง",
                "verbose_name_plural": "ไฟล์เสียง",
            },
        ),
        migrations.CreateModel(
            name="GrammarPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("2.0", "HSK 2.0 (ใช้อยู่ปัจจุบัน)"),
                            ("3.0", "HSK 3.0 (มาตรฐานใหม่)"),
                        ],
                        db_index=True,
                        default="2.0",
                        max_length=8,
                        verbose_name="มาตรฐาน",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            (
                                "official_past_paper",
                                "ข้อสอบเก่าทางการ (ลิขสิทธิ์ ห้ามขาย)",
                            ),
                            ("textbook", "หนังสือเตรียมสอบ (ลิขสิทธิ์ ห้ามขาย)"),
                            ("ai_generated", "สร้างด้วย AI"),
                            ("hand_written", "เขียนเอง"),
                            ("public_domain", "สาธารณสมบัติ"),
                        ],
                        db_index=True,
                        default="hand_written",
                        max_length=32,
                        verbose_name="ที่มา",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True,
                        help_text="เช่น H51001 หน้า 3 ข้อ 46",
                        max_length=200,
                        verbose_name="อ้างอิงที่มา",
                    ),
                ),
                (
                    "commercial_safe",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="ปิดเสมอสำหรับข้อสอบเก่าและเนื้อหาจากหนังสือ",
                        verbose_name="ใช้เชิงพาณิชย์ได้",
                    ),
                ),
                (
                    "title_zh",
                    models.CharField(max_length=120, verbose_name="หัวข้อ (จีน)"),
                ),
                (
                    "title_th",
                    models.CharField(max_length=160, verbose_name="หัวข้อ (ไทย)"),
                ),
                (
                    "hsk_level",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="ระดับ HSK"
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("listening", "听力 ฟัง"),
                            ("reading", "阅读 อ่าน"),
                            ("writing", "书写 เขียน"),
                            ("vocab", "คำศัพท์ (ฝึกเอง ไม่ใช่พาร์ทในข้อสอบ)"),
                        ],
                        default="writing",
                        max_length=16,
                        verbose_name="พาร์ทที่ใช้",
                    ),
                ),
                ("explanation_th", models.TextField(verbose_name="คำอธิบาย (ไทย)")),
                (
                    "patterns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='เช่น ["随着 + N的 + 变化，+ ประโยคหลัก"]',
                        verbose_name="รูปประโยค",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=50,
                        help_text="น้อย = สำคัญกว่า",
                        verbose_name="ลำดับความสำคัญ",
                    ),
                ),
            ],
            options={
                "verbose_name": "จุดไวยากรณ์",
                "verbose_name_plural": "จุดไวยากรณ์",
                "ordering": ["priority", "title_zh"],
            },
        ),
        migrations.CreateModel(
            name="SynonymGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, verbose_name="ชื่อกลุ่ม")),
                ("note_th", models.TextField(verbose_name="วิธีแยกความต่าง (ไทย)")),
            ],
            options={
                "verbose_name": "กลุ่มคำใกล้เคียง",
                "verbose_name_plural": "กลุ่มคำใกล้เคียง",
            },
        ),
        migrations.CreateModel(
            name="WritingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("2.0", "HSK 2.0 (ใช้อยู่ปัจจุบัน)"),
                            ("3.0", "HSK 3.0 (มาตรฐานใหม่)"),
                        ],
                        db_index=True,
                        default="2.0",
                        max_length=8,
                        verbose_name="มาตรฐาน",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            (
                                "official_past_paper",
                                "ข้อสอบเก่าทางการ (ลิขสิทธิ์ ห้ามขาย)",
                            ),
                            ("textbook", "หนังสือเตรียมสอบ (ลิขสิทธิ์ ห้ามขาย)"),
                            ("ai_generated", "สร้างด้วย AI"),
                            ("hand_written", "เขียนเอง"),
                            ("public_domain", "สาธารณสมบัติ"),
                        ],
                        db_index=True,
                        default="hand_written",
                        max_length=32,
                        verbose_name="ที่มา",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True,
                        help_text="เช่น H51001 หน้า 3 ข้อ 46",
                        max_length=200,
                        verbose_name="อ้างอิงที่มา",
                    ),
                ),
                (
                    "commercial_safe",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="ปิดเสมอสำหรับข้อสอบเก่าและเนื้อหาจากหนังสือ",
                        verbose_name="ใช้เชิงพาณิชย์ได้",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="ชื่อเทมเพลต")),
                ("body_zh", models.TextField(verbose_name="เทมเพลต (จีน)")),
                ("body_th", models.TextField(verbose_name="คำอธิบาย (ไทย)")),
                (
                    "approx_chars",
                    models.PositiveSmallIntegerField(
                        default=90, verbose_name="ความยาวโดยประมาณ"
                    ),
                ),
                (
                    "use_case",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="ใช้กับโจทย์แบบไหน"
                    ),
                ),
            ],
            options={
                "verbose_name": "เทมเพลตเรียงความ",
                "verbose_name_plural": "เทมเพลตเรียงความ",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("learner", "ผู้เรียน"),
                            ("coach", "โค้ช / ผู้ปกครอง / ครู"),
                            ("admin", "ผู้ดูแลระบบ"),
                        ],
                        db_index=True,
                        default="learner",
                        max_length=16,
                        verbose_name="บทบาท",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="ชื่อที่แสดง"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Bangkok", max_length=64, verbose_name="เขตเวลา"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "ผู้ใช้",
                "verbose_name_plural": "ผู้ใช้",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ExamSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("2.0", "HSK 2.0 (ใช้อยู่ปัจจุบัน)"),
                            ("3.0", "HSK 3.0 (มาตรฐานใหม่)"),
                        ],
                        max_length=8,
                        verbose_name="มาตรฐาน",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(default=5, verbose_name="ระดับ"),
                ),
                (
                    "vocab_size",
                    models.PositiveIntegerField(verbose_name="จำนวนคำศัพท์สะสม"),
                ),
                (
                    "total_score",
                    models.PositiveSmallIntegerField(
                        default=300, verbose_name="คะแนนเต็ม"
                    ),
                ),
                (
                    "pass_score",
                    models.PositiveSmallIntegerField(
                        default=180, verbose_name="คะแนนผ่าน"
                    ),
                ),
                (
                    "per_section_minimum",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="ว่าง = ไม่มีขั้นต่ำ ตัดสินที่คะแนนรวมอย่างเดียว (HSK5 2.0 เป็นแบบนี้)",
                        null=True,
                        verbose_name="ขั้นต่ำรายพาร์ท",
                    ),
                ),
                (
                    "sections",
                    models.JSONField(
                        default=dict,
                        help_text='เช่น {"listening": {"questions": 45, "minutes": 30, "numbers": [1, 45]}}',
                        verbose_name="โครงสร้างพาร์ท",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="ใช้อยู่ปัจจุบัน"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="หมายเหตุ")),
            ],
            options={
                "verbose_name": "สเปกข้อสอบ",
                "verbose_name_plural": "สเปกข้อสอบ",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("standard", "level"), name="uniq_spec_standard_level"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("2.0", "HSK 2.0 (ใช้อยู่ปัจจุบัน)"),
                            ("3.0", "HSK 3.0 (มาตรฐานใหม่)"),
                        ],
                        db_index=True,
                        default="2.0",
                        max_length=8,
                        verbose_name="มาตรฐาน",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            (
                                "official_past_paper",
                                "ข้อสอบเก่าทางการ (ลิขสิทธิ์ ห้ามขาย)",
                            ),
                            ("textbook", "หนังสือเตรียมสอบ (ลิขสิทธิ์ ห้ามขาย)"),
                            ("ai_generated", "สร้างด้วย AI"),
                            ("hand_written", "เขียนเอง"),
                            ("public_domain", "สาธารณสมบัติ"),
                        ],
                        db_index=True,
                        default="hand_written",
                        max_length=32,
                        verbose_name="ที่มา",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True,
                        help_text="เช่น H51001 หน้า 3 ข้อ 46",
                        max_length=200,
                        verbose_name="อ้างอิงที่มา",
                    ),
                ),
                (
                    "commercial_safe",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="ปิดเสมอสำหรับข้อสอบเก่าและเนื้อหาจากหนังสือ",
                        verbose_name="ใช้เชิงพาณิชย์ได้",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("listening_dialog", "บทสนทนาสั้น (听力第一部分)"),
                            ("listening_passage", "บทยาว (听力第二部分)"),
                            ("reading_cloze", "เติมคำในช่องว่าง (阅读第一部分)"),
                            ("reading_match", "เลือกประโยคที่ตรง (阅读第二部分)"),
                            ("reading_passage", "บทอ่านยาว (阅读第三部分)"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="ชนิด",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("listening", "听力 ฟัง"),
                            ("reading", "阅读 อ่าน"),
                            ("writing", "书写 เขียน"),
                            ("vocab", "คำศัพท์ (ฝึกเอง ไม่ใช่พาร์ทในข้อสอบ)"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="พาร์ท",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="หัวเรื่อง"
                    ),
                ),
                (
                    "passage_zh",
                    models.TextField(blank=True, verbose_name="เนื้อหา (จีน)"),
                ),
                (
                    "passage_th",
                    models.TextField(blank=True, verbose_name="คำแปล (ไทย)"),
                ),
                (
                    "char_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="จำนวนตัวอักษร"
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="1 ง่ายสุด – 5 ยากสุด",
                        verbose_name="ความยาก",
                    ),
                ),
                (
                    "audio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="groups",
                        to="core.audioclip",
                        verbose_name="ไฟล์เสียง",
                    ),
                ),
            ],
            options={
                "verbose_name": "ชุดเนื้อหา",
                "verbose_name_plural": "ชุดเนื้อหา",
            },
        ),
        migrations.CreateModel(
            name="LearnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_level",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="ระดับเป้าหมาย"
                    ),
                ),
                ("target_exam_date", models.DateField(verbose_name="วันสอบเป้าหมาย")),
                (
                    "backup_exam_date",
                    models.DateField(blank=True, null=True, verbose_name="วันสอบสำรอง"),
                ),
                (
                    "daily_minutes_budget",
                    models.PositiveSmallIntegerField(
                        default=210, verbose_name="งบเวลาต่อวัน (นาที)"
                    ),
                ),
                (
                    "new_words_per_day",
                    models.PositiveSmallIntegerField(
                        default=14,
                        help_text="ตัวคุมโหลดจะลดค่านี้เองเมื่อของค้างเกินเพดาน",
                        verbose_name="คำใหม่ต่อวัน",
                    ),
                ),
                (
                    "drill_size",
                    models.PositiveSmallIntegerField(
                        default=40,
                        help_text="คงที่โดยตั้งใจ — ส่วนผสมเปลี่ยน ไม่ใช่จำนวน (CLAUDE.md D7)",
                        verbose_name="ขนาดชุดข้อสอบรายวัน",
                    ),
                ),
                (
                    "baseline_listening",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="คะแนนฐาน ฟัง"
                    ),
                ),
                (
                    "baseline_reading",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="คะแนนฐาน อ่าน"
                    ),
                ),
                (
                    "baseline_writing",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="คะแนนฐาน เขียน"
                    ),
                ),
                (
                    "baseline_taken_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="วันที่วัดคะแนนฐาน"
                    ),
                ),
                (
                    "known_vocab_estimate",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="จากการวัดจริงหรือจากครูผู้สอน ไม่ใช่การเดา",
                        null=True,
                        verbose_name="ประมาณจำนวนคำที่รู้",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="บันทึก")),
                (
                    "coaches",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role__in": ["coach", "admin"]},
                        related_name="coached_learners",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="โค้ชที่ดูข้อมูลได้",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learner_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้",
                    ),
                ),
            ],
            options={
                "verbose_name": "โปรไฟล์ผู้เรียน",
                "verbose_name_plural": "โปรไฟล์ผู้เรียน",
            },
        ),
        migrations.CreateModel(
            name="DrillSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="เริ่ม"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="จบ"),
                ),
                (
                    "planned_size",
                    models.PositiveSmallIntegerField(
                        default=40, verbose_name="จำนวนข้อที่วางไว้"
                    ),
                ),
                (
                    "answered",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ตอบไปแล้ว"
                    ),
                ),
                (
                    "correct",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ถูก"),
                ),
                (
                    "mix",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='เช่น {"due": 20, "wrong": 12, "new": 8} — เก็บไว้เพื่อย้อนดูว่าวันนั้นระบบเลือกยังไง',
                        verbose_name="ส่วนผสมที่ใช้จริง",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="core.learnerprofile",
                        verbose_name="ผู้เรียน",
                    ),
                ),
            ],
            options={
                "verbose_name": "เซสชันฝึก",
                "verbose_name_plural": "เซสชันฝึก",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DictationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("typed_text", models.TextField(blank=True, verbose_name="ที่พิมพ์")),
                (
                    "char_diff",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='เช่น [{"i": 3, "expected": "在", "got": "再", "type": "HOMOPHONE"}]',
                        verbose_name="ผลเทียบตัวอักษร",
                    ),
                ),
                (
                    "accuracy_pct",
                    models.FloatField(default=0, verbose_name="ความแม่น (%)"),
                ),
                (
                    "replay_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="เปิดฟังซ้ำกี่ครั้ง"
                    ),
                ),
                (
                    "playback_rate",
                    models.FloatField(default=1.0, verbose_name="ความเร็วที่ใช้ฟัง"),
                ),
                (
                    "clip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dictations",
                        to="core.audioclip",
                        verbose_name="ไฟล์เสียง",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dictations",
                        to="core.learnerprofile",
                        verbose_name="ผู้เรียน",
                    ),
                ),
            ],
            options={
                "verbose_name": "การฝึก 听写",
                "verbose_name_plural": "การฝึก 听写",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="วันที่")),
                (
                    "answered",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ตอบไปกี่ข้อ"
                    ),
                ),
                (
                    "correct",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ถูกกี่ข้อ"
                    ),
                ),
                (
                    "minutes",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="นาทีที่ใช้"
                    ),
                ),
                (
                    "new_words",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="คำใหม่วันนี้"
                    ),
                ),
                (
                    "cumulative_words",
                    models.PositiveIntegerField(default=0, verbose_name="คำสะสม"),
                ),
                (
                    "met_goal",
                    models.BooleanField(default=False, verbose_name="ถึงเป้าของวัน"),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_records",
                        to="core.learnerprofile",
                        verbose_name="ผู้เรียน",
                    ),
                ),
            ],
            options={
                "verbose_name": "สรุปรายวัน",
                "verbose_name_plural": "สรุปรายวัน",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("recognize", "อ่าน 汉字 → ความหมาย"),
                            ("audio", "ฟังเสียง → ความหมาย"),
                            ("cloze", "เติมคำในช่องว่าง / แยกคำใกล้เคียง"),
                            ("produce", "ความหมาย → พิมพ์ 汉字"),
                        ],
                        default="recognize",
                        max_length=16,
                        verbose_name="ชนิดการ์ด",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "ยังไม่เคยเรียน"),
                            ("learning", "กำลังเรียน"),
                            ("review", "อยู่ในรอบทบทวน"),
                            ("lapsed", "เคยจำได้แล้วลืม"),
                            ("suspended", "พักไว้"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=16,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="ถึงกำหนดทบทวน",
                    ),
                ),
                (
                    "interval_days",
                    models.FloatField(default=0, verbose_name="ระยะห่างปัจจุบัน (วัน)"),
                ),
                ("ease", models.FloatField(default=2.5, verbose_name="ค่าความง่าย")),
                (
                    "reps",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ทบทวนไปกี่ครั้ง"
                    ),
                ),
                (
                    "lapses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ลืมไปกี่ครั้ง"
                    ),
                ),
                (
                    "last_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ทบทวนล่าสุด"
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="core.learnerprofile",
                        verbose_name="ผู้เรียน",
                    ),
                ),
            ],
            options={
                "verbose_name": "การ์ดทบทวน",
                "verbose_name_plural": "การ์ดทบทวน",
            },
        ),
        migrations.CreateModel(
            name="MockExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("taken_on", models.DateField(db_index=True, verbose_name="วันที่ทำ")),
                (
                    "paper_ref",
                    models.CharField(
                        blank=True,
                        help_text="เช่น H51001",
                        max_length=64,
                        verbose_name="ชุดข้อสอบ",
                    ),
                ),
                (
                    "is_timed",
                    models.BooleanField(default=True, verbose_name="จับเวลาจริง"),
                ),
                (
                    "listening",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ฟัง"),
                ),
                (
                    "reading",
                    models.PositiveSmallIntegerField(default=0, verbose_name="อ่าน"),
                ),
                (
                    "writing",
                    models.PositiveSmallIntegerField(default=0, verbose_name="เขียน"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="บันทึก")),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_exams",
                        to="core.learnerprofile",
                        verbose_name="ผู้เรียน",
                    ),
                ),
                (
                    "spec",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mock_exams",
                        to="core.examspec",
                        verbose_name="สเปกข้อสอบ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ข้อสอบจำลอง",
                "verbose_name_plural": "ข้อสอบจำลอง",
                "ordering": ["-taken_on"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("2.0", "HSK 2.0 (ใช้อยู่ปัจจุบัน)"),
                            ("3.0", "HSK 3.0 (มาตรฐานใหม่)"),
                        ],
                        db_index=True,
                        default="2.0",
                        max_length=8,
                        verbose_name="มาตรฐาน",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            (
                                "official_past_paper",
                                "ข้อสอบเก่าทางการ (ลิขสิทธิ์ ห้ามขาย)",
                            ),
                            ("textbook", "หนังสือเตรียมสอบ (ลิขสิทธิ์ ห้ามขาย)"),
                            ("ai_generated", "สร้างด้วย AI"),
                            ("hand_written", "เขียนเอง"),
                            ("public_domain", "สาธารณสมบัติ"),
                        ],
                        db_index=True,
                        default="hand_written",
                        max_length=32,
                        verbose_name="ที่มา",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True,
                        help_text="เช่น H51001 หน้า 3 ข้อ 46",
                        max_length=200,
                        verbose_name="อ้างอิงที่มา",
                    ),
                ),
                (
                    "commercial_safe",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="ปิดเสมอสำหรับข้อสอบเก่าและเนื้อหาจากหนังสือ",
                        verbose_name="ใช้เชิงพาณิชย์ได้",
                    ),
                ),
                (
                    "qtype",
                    models.CharField(
                        choices=[
                            ("vocab_mc", "คำศัพท์ปรนัย"),
                            ("vocab_recall", "นึกคำจากความหมาย"),
                            ("synonym_cloze", "เลือกคำใกล้เคียงให้ตรงบริบท"),
                            ("word_order", "เรียงคำเป็นประโยค (完成句子)"),
                            ("reading_mc", "อ่านแล้วตอบปรนัย"),
                            ("listening_mc", "ฟังแล้วตอบปรนัย"),
                            ("dictation", "听写 ฟังแล้วพิมพ์"),
                            ("writing_prompt", "โจทย์เขียนเรียงความ"),
                        ],
                        db_index=True,
                        max_length=24,
                        verbose_name="ชนิดคำถาม",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("listening", "听力 ฟัง"),
                            ("reading", "阅读 อ่าน"),
                            ("writing", "书写 เขียน"),
                            ("vocab", "คำศัพท์ (ฝึกเอง ไม่ใช่พาร์ทในข้อสอบ)"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="พาร์ท",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "ร่าง"),
                            ("active", "ใช้งาน"),
                            ("suspended", "พักไว้ (สงสัยเฉลยผิด)"),
                            ("retired", "เลิกใช้"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                        verbose_name="สถานะ",
                    ),
                ),
                ("prompt_zh", models.TextField(verbose_name="โจทย์ (จีน)")),
                (
                    "prompt_th",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="คำสั่ง (ไทย)"
                    ),
                ),
                (
                    "answer_text",
                    models.CharField(
                        blank=True,
                        help_text="ใช้กับข้อที่ไม่ใช่ปรนัย เช่น เรียงคำ หรือ 听写",
                        max_length=400,
                        verbose_name="เฉลย (ข้อเขียน)",
                    ),
                ),
                (
                    "explanation_th",
                    models.TextField(blank=True, verbose_name="คำอธิบายเฉลย (ไทย)"),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=3, verbose_name="ความยาก"
                    ),
                ),
                (
                    "target_seconds",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="阅读第三部分 ควรอยู่ที่ 70 วินาที เกิน 105 ให้เดาแล้วไปต่อ",
                        verbose_name="เวลาเป้าหมาย (วินาที)",
                    ),
                ),
                (
                    "flagged_wrong_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="ผู้เรียนกดรายงานกี่ครั้ง — เกิน 0 ควรตรวจด้วยตาคน",
                        verbose_name="ถูกรายงานว่าเฉลยผิด",
                    ),
                ),
                (
                    "grammar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="core.grammarpoint",
                        verbose_name="จุดไวยากรณ์",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.itemgroup",
                        verbose_name="ชุดเนื้อหา",
                    ),
                ),
                (
                    "synonym_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="core.synonymgroup",
                        verbose_name="กลุ่มคำใกล้เคียง",
                    ),
                ),
            ],
            options={
                "verbose_name": "คำถาม",
                "verbose_name_plural": "คำถาม",
            },
        ),
        migrations.CreateModel(
            name="AnswerRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "given",
                    models.CharField(
                        blank=True, max_length=400, verbose_name="คำตอบที่ให้"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="ถูก"
                    ),
                ),
                (
                    "elapsed_ms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ใช้เวลา (มิลลิวินาที)"
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VOCAB", "ไม่รู้คำศัพท์คำนั้นเลย"),
                            ("MEANING", "รู้คำ แต่เลือกความหมายผิดในบริบท"),
                            ("STRUCTURE", "รู้คำครบ แต่จับโครงสร้างประโยคผิด"),
                            ("TOO_SLOW", "รู้คำตอบ แต่ไม่ทันเวลา"),
                            ("SOUND", "ฟังไม่ออกทั้งที่รู้คำนั้น"),
                            ("CARELESS", "เผลอ อ่านโจทย์ไม่ครบ"),
                        ],
                        db_index=True,
                        help_text="ผู้เรียนเป็นคนติดป้ายเอง — นี่คือข้อมูลที่มีค่าที่สุดของทั้งระบบ",
                        max_length=16,
                        verbose_name="สาเหตุที่ผิด",
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="เวลาที่ตอบ"),
                ),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answers",
                        to="core.card",
                        verbose_name="การ์ด",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="core.drillsession",
                        verbose_name="เซสชัน",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answers",
                        to="core.question",
                        verbose_name="คำถาม",
                    ),
                ),
            ],
            options={
                "verbose_name": "คำตอบ",
                "verbose_name_plural": "คำตอบ",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=400, verbose_name="ตัวเลือก")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="เป็นคำตอบที่ถูก"),
                ),
                (
                    "distractor_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("near_synonym", "คำใกล้เคียงความหมาย"),
                            ("same_char", "ใช้ตัวอักษรร่วมกัน"),
                            ("homophone", "เสียงเหมือน/ใกล้เคียง"),
                            ("wrong_collocation", "คำที่ไม่เข้าคู่กับคำข้างเคียง"),
                            ("plausible_fabric", "สมเหตุสมผลแต่บทไม่ได้พูด"),
                            ("overgeneral", "กว้าง/เหมารวมเกินไป"),
                        ],
                        max_length=24,
                        verbose_name="ชนิดตัวลวง",
                    ),
                ),
                (
                    "rationale_th",
                    models.CharField(
                        blank=True, max_length=400, verbose_name="ทำไมผิด (ไทย)"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ลำดับ"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="core.question",
                        verbose_name="คำถาม",
                    ),
                ),
            ],
            options={
                "verbose_name": "ตัวเลือก",
                "verbose_name_plural": "ตัวเลือก",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReviewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="เวลา"
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "ลืม"), (2, "ยาก"), (3, "จำได้"), (4, "ง่าย")],
                        verbose_name="ผล",
                    ),
                ),
                (
                    "elapsed_ms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ใช้เวลา (มิลลิวินาที)"
                    ),
                ),
                (
                    "prev_interval_days",
                    models.FloatField(default=0, verbose_name="ระยะห่างก่อนหน้า"),
                ),
                (
                    "new_interval_days",
                    models.FloatField(default=0, verbose_name="ระยะห่างใหม่"),
                ),
                (
                    "scheduler_version",
                    models.CharField(
                        default="sm2d-1",
                        max_length=16,
                        verbose_name="เวอร์ชันตัวจัดตาราง",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.card",
                        verbose_name="การ์ด",
                    ),
                ),
            ],
            options={
                "verbose_name": "ประวัติการทบทวน",
                "verbose_name_plural": "ประวัติการทบทวน",
                "ordering": ["-reviewed_at"],
            },
        ),
        migrations.CreateModel(
            name="VocabItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("2.0", "HSK 2.0 (ใช้อยู่ปัจจุบัน)"),
                            ("3.0", "HSK 3.0 (มาตรฐานใหม่)"),
                        ],
                        db_index=True,
                        default="2.0",
                        max_length=8,
                        verbose_name="มาตรฐาน",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            (
                                "official_past_paper",
                                "ข้อสอบเก่าทางการ (ลิขสิทธิ์ ห้ามขาย)",
                            ),
                            ("textbook", "หนังสือเตรียมสอบ (ลิขสิทธิ์ ห้ามขาย)"),
                            ("ai_generated", "สร้างด้วย AI"),
                            ("hand_written", "เขียนเอง"),
                            ("public_domain", "สาธารณสมบัติ"),
                        ],
                        db_index=True,
                        default="hand_written",
                        max_length=32,
                        verbose_name="ที่มา",
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True,
                        help_text="เช่น H51001 หน้า 3 ข้อ 46",
                        max_length=200,
                        verbose_name="อ้างอิงที่มา",
                    ),
                ),
                (
                    "commercial_safe",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="ปิดเสมอสำหรับข้อสอบเก่าและเนื้อหาจากหนังสือ",
                        verbose_name="ใช้เชิงพาณิชย์ได้",
                    ),
                ),
                (
                    "hanzi",
                    models.CharField(db_index=True, max_length=32, verbose_name="汉字"),
                ),
                ("pinyin", models.CharField(max_length=96, verbose_name="pinyin")),
                (
                    "meaning_th",
                    models.CharField(max_length=255, verbose_name="ความหมาย (ไทย)"),
                ),
                (
                    "meaning_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ความหมาย (อังกฤษ)"
                    ),
                ),
                (
                    "pos",
                    models.CharField(blank=True, max_length=24, verbose_name="ชนิดคำ"),
                ),
                (
                    "hsk_level",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=5, verbose_name="ระดับ HSK"
                    ),
                ),
                (
                    "frequency_rank",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="เลขน้อย = เจอบ่อยกว่า ใช้จัดลำดับว่าควรเรียนคำไหนก่อน",
                        null=True,
                        verbose_name="อันดับความถี่",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='เช่น ["conn", "idiom"] — conn = คำเชื่อมที่ใช้ในเรียงความ',
                        verbose_name="แท็ก",
                    ),
                ),
                (
                    "example_zh",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ประโยคตัวอย่าง"
                    ),
                ),
                (
                    "example_th",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="แปลประโยค"
                    ),
                ),
                (
                    "audio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vocab_items",
                        to="core.audioclip",
                        verbose_name="ไฟล์เสียง",
                    ),
                ),
            ],
            options={
                "verbose_name": "คำศัพท์",
                "verbose_name_plural": "คำศัพท์",
                "ordering": ["frequency_rank", "hanzi"],
            },
        ),
        migrations.AddField(
            model_name="synonymgroup",
            name="items",
            field=models.ManyToManyField(
                related_name="synonym_groups",
                to="core.vocabitem",
                verbose_name="คำในกลุ่ม",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="vocab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="core.vocabitem",
                verbose_name="คำศัพท์ที่ทดสอบ",
            ),
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("VOCAB", "ไม่รู้คำศัพท์คำนั้นเลย"),
                            ("MEANING", "รู้คำ แต่เลือกความหมายผิดในบริบท"),
                            ("STRUCTURE", "รู้คำครบ แต่จับโครงสร้างประโยคผิด"),
                            ("TOO_SLOW", "รู้คำตอบ แต่ไม่ทันเวลา"),
                            ("SOUND", "ฟังไม่ออกทั้งที่รู้คำนั้น"),
                            ("CARELESS", "เผลอ อ่านโจทย์ไม่ครบ"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="สาเหตุ",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("listening", "听力 ฟัง"),
                            ("reading", "阅读 อ่าน"),
                            ("writing", "书写 เขียน"),
                            ("vocab", "คำศัพท์ (ฝึกเอง ไม่ใช่พาร์ทในข้อสอบ)"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="พาร์ท",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="คำ ประโยค หรือหัวข้อไวยากรณ์ — เก็บเป็นข้อความเพื่อให้ยังอ่านออกแม้ลบ FK ทิ้ง",
                        max_length=200,
                        verbose_name="สิ่งที่ผิด",
                    ),
                ),
                (
                    "miss_count",
                    models.PositiveIntegerField(
                        db_index=True, default=1, verbose_name="ผิดไปกี่ครั้ง"
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ผิดครั้งแรก"),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="ผิดล่าสุด",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="แก้ได้แล้วเมื่อ"
                    ),
                ),
                (
                    "grammar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="errors",
                        to="core.grammarpoint",
                        verbose_name="จุดไวยากรณ์",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="core.learnerprofile",
                        verbose_name="ผู้เรียน",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="errors",
                        to="core.question",
                        verbose_name="คำถามล่าสุดที่ผิด",
                    ),
                ),
                (
                    "vocab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="errors",
                        to="core.vocabitem",
                        verbose_name="คำศัพท์",
                    ),
                ),
            ],
            options={
                "verbose_name": "บันทึกข้อผิด",
                "verbose_name_plural": "บันทึกข้อผิด",
                "ordering": ["-miss_count", "-last_seen_at"],
            },
        ),
        migrations.AddField(
            model_name="card",
            name="vocab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="core.vocabitem",
                verbose_name="คำศัพท์",
            ),
        ),
        migrations.CreateModel(
            name="WritingSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("prompt_zh", models.TextField(verbose_name="โจทย์")),
                ("text_zh", models.TextField(verbose_name="งานเขียน")),
                (
                    "char_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="จำนวนตัวอักษรจีน"
                    ),
                ),
                (
                    "minutes_spent",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="นาทีที่ใช้"
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writings",
                        to="core.learnerprofile",
                        verbose_name="ผู้เรียน",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="core.writingtemplate",
                        verbose_name="เทมเพลตที่ใช้",
                    ),
                ),
            ],
            options={
                "verbose_name": "งานเขียนที่ส่ง",
                "verbose_name_plural": "งานเขียนที่ส่ง",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WritingFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scores",
                    models.JSONField(
                        default=dict,
                        help_text='{"content": 6, "grammar": 5, "vocabulary": 4, "coherence": 3, "form": 3}',
                        verbose_name="คะแนนรายมิติ",
                    ),
                ),
                (
                    "total_100",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="คะแนนเต็ม 100"
                    ),
                ),
                (
                    "issues",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"wrong": "...", "right": "...", "why": "...", "kind": "grammar"}]',
                        verbose_name="จุดผิดรายจุด",
                    ),
                ),
                (
                    "graded_by",
                    models.CharField(
                        blank=True,
                        help_text="ชื่อโมเดล หรือชื่อครู",
                        max_length=64,
                        verbose_name="ตรวจโดย",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="core.writingsubmission",
                        verbose_name="งานเขียน",
                    ),
                ),
            ],
            options={
                "verbose_name": "ผลตรวจงานเขียน",
                "verbose_name_plural": "ผลตรวจงานเขียน",
            },
        ),
        migrations.AddIndex(
            model_name="drillsession",
            index=models.Index(
                fields=["learner", "-started_at"], name="core_drills_learner_2d87db_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyrecord",
            constraint=models.UniqueConstraint(
                fields=("learner", "date"), name="uniq_daily_learner_date"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewlog",
            index=models.Index(
                fields=["card", "-reviewed_at"], name="core_review_card_id_e0f5b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vocabitem",
            index=models.Index(
                fields=["hsk_level", "frequency_rank"],
                name="core_vocabi_hsk_lev_1189c3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="vocabitem",
            constraint=models.UniqueConstraint(
                fields=("hanzi", "standard"), name="uniq_vocab_hanzi_standard"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["section", "qtype", "status"],
                name="core_questi_section_322e6d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["status", "difficulty"], name="core_questi_status_62a5c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["learner", "resolved_at", "-miss_count"],
                name="core_errorl_learner_89f5bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["learner", "-last_seen_at"],
                name="core_errorl_learner_499642_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="errorlog",
            constraint=models.UniqueConstraint(
                fields=("learner", "code", "label"),
                name="uniq_error_learner_code_label",
            ),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["learner", "state", "due_at"],
                name="core_card_learner_033c0f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["learner", "due_at"], name="core_card_learner_d70a64_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="card",
            constraint=models.UniqueConstraint(
                fields=("learner", "vocab", "card_type"),
                name="uniq_card_learner_vocab_type",
            ),
        ),
    ]
