# Generated by Django 5.2.5 on 2026-08-26 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='เริ่ม')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='เสร็จ')),
                ('planned_size', models.PositiveSmallIntegerField(default=80, verbose_name='จำนวนคำที่วัด')),
                ('result', models.JSONField(blank=True, default=dict, help_text='เช่น {"by_level": {"4": {"asked": 20, "known": 14}}, "known_vocab_estimate": 1420}', verbose_name='ผลที่คำนวณได้')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_tests', to='core.learnerprofile', verbose_name='ผู้เรียน')),
            ],
            options={
                'verbose_name': 'แบบวัดระดับ',
                'verbose_name_plural': 'แบบวัดระดับ',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsk_level', models.PositiveSmallIntegerField(db_index=True, verbose_name='ระดับของคำ')),
                ('given', models.CharField(blank=True, max_length=255, verbose_name='คำตอบที่เลือก')),
                ('is_correct', models.BooleanField(default=False, verbose_name='ถูก')),
                ('said_unknown', models.BooleanField(default=False, verbose_name='กดว่ายังไม่รู้')),
                ('elapsed_ms', models.PositiveIntegerField(default=0, verbose_name='ใช้เวลา (มิลลิวินาที)')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='ตอบเมื่อ')),
                ('vocab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_answers', to='core.vocabitem', verbose_name='คำศัพท์')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.placementtest', verbose_name='แบบวัดระดับ')),
            ],
            options={
                'verbose_name': 'คำตอบในแบบวัดระดับ',
                'verbose_name_plural': 'คำตอบในแบบวัดระดับ',
                'ordering': ['answered_at'],
                'constraints': [models.UniqueConstraint(fields=('test', 'vocab'), name='uniq_placement_test_vocab')],
            },
        ),
    ]
