# Generated by Django 5.2.5 on 2026-08-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_placementtest_placementanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabitem',
            name='exam_as_answer',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='เป็นเฉลยกี่ครั้ง'),
        ),
        migrations.AddField(
            model_name='vocabitem',
            name='exam_as_distractor',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='เป็นตัวลวงกี่ครั้ง'),
        ),
        migrations.AddField(
            model_name='vocabitem',
            name='exam_evidence',
            field=models.JSONField(blank=True, default=dict, help_text='เช่น {"papers": ["H51001"], "sections": {"reading": 12}}', verbose_name='รายละเอียดจากข้อสอบ'),
        ),
        migrations.AddField(
            model_name='vocabitem',
            name='exam_occurrences',
            field=models.PositiveIntegerField(default=0, verbose_name='พบทั้งหมดกี่ครั้ง'),
        ),
        migrations.AddField(
            model_name='vocabitem',
            name='exam_papers_count',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='จำนวนชุดข้อสอบ (จาก 9 ชุด) ที่พบคำนี้ — ตัวชี้วัดหลักว่าคำไหนต้องรู้', verbose_name='พบในกี่ชุด'),
        ),
        migrations.AddIndex(
            model_name='vocabitem',
            index=models.Index(fields=['-exam_papers_count', '-exam_occurrences'], name='core_vocabi_exam_pa_ca260d_idx'),
        ),
    ]
