# Generated by Django 5.2.5 on 2026-08-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vocabitem_exam_as_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillsession',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ทำถึงข้อที่'),
        ),
        migrations.AddField(
            model_name='drillsession',
            name='queue',
            field=models.JSONField(blank=True, default=list, help_text='เช่น [{"kind": "vocab", "id": 12, "source": "due"}]', verbose_name='คิวข้อที่ล็อกไว้'),
        ),
    ]
