# Generated by Django 5.2.5 on 2026-08-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_drillsession_position_drillsession_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabitem',
            name='collocations',
            field=models.JSONField(blank=True, default=list, help_text='เช่น ["采取措施", "采取行动"]', verbose_name='คำที่จับคู่กันบ่อย'),
        ),
        migrations.AddField(
            model_name='vocabitem',
            name='confusable_with',
            field=models.JSONField(blank=True, default=list, help_text='เช่น [{"hanzi": "私人", "how_to_tell": "...", "seen_together_in_exam": true}]', verbose_name='คำที่สับสนกันได้'),
        ),
    ]
