# Generated by Django 5.2.5 on 2026-08-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vocabitem_collocations_vocabitem_confusable_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.JSONField(blank=True, default=dict, help_text='{"why_correct": "...", "hint": "...", "key_vocab": [...], "rule": "...", "error_code": "..."}', verbose_name='คำอธิบาย 4 ชั้น'),
        ),
    ]
