# Generated by Django 5.2.5 on 2026-08-26 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_question_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplanationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verdict', models.CharField(choices=[('wrong', 'คำอธิบายนี้ผิด'), ('corrected', 'ผิด และนี่คือคำอธิบายที่ถูก'), ('confirmed', 'ตรวจแล้ว ถูกต้อง')], db_index=True, max_length=16, verbose_name='ผลการตรวจ')),
                ('body', models.TextField(blank=True, help_text='สิ่งที่ผู้ใช้ค้นมาได้ — จะถูกแสดงแทนของ AI เมื่อเจ้าของระบบรับแล้ว', verbose_name='คำอธิบายที่ถูกต้อง')),
                ('source', models.CharField(blank=True, help_text='เช่น ครูที่สอน · หนังสือเตรียมสอบหน้า 42 · ลิงก์', max_length=300, verbose_name='อ้างอิงจากไหน')),
                ('status', models.CharField(choices=[('open', 'รอเจ้าของระบบดู'), ('accepted', 'รับมาใช้แทนคำอธิบายเดิม'), ('rejected', 'ไม่รับ')], db_index=True, default='open', max_length=16, verbose_name='สถานะ')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='explanation_notes', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ส่ง')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.question', verbose_name='คำถาม')),
            ],
            options={
                'verbose_name': 'การตรวจคำอธิบาย',
                'verbose_name_plural': 'การตรวจคำอธิบาย',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['question', '-created_at'], name='core_explan_questio_d55487_idx')],
            },
        ),
    ]
