# Generated by Django 5.2.5 on 2026-08-26 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_explanationnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanationnote',
            name='vocab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.vocabitem', verbose_name='คำศัพท์'),
        ),
        migrations.AlterField(
            model_name='explanationnote',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.question', verbose_name='คำถาม'),
        ),
        migrations.AddIndex(
            model_name='explanationnote',
            index=models.Index(fields=['vocab', '-created_at'], name='core_explan_vocab_i_2be2d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='explanationnote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('question__isnull', False), ('vocab__isnull', True)), models.Q(('question__isnull', True), ('vocab__isnull', False)), _connector='OR'), name='note_targets_exactly_one'),
        ),
    ]
