# Generated by Django 5.2.5 on 2026-08-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_explanationnote_vocab_alter_explanationnote_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockexam',
            name='answers',
            field=models.JSONField(blank=True, default=dict, help_text='{"<question_id>": "ข้อความตัวเลือก"}', verbose_name='คำตอบที่เลือก'),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='auto_submitted',
            field=models.BooleanField(default=False, verbose_name='หมดเวลาแล้วส่งอัตโนมัติ'),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='correct_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ตอบถูกกี่ข้อ'),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ส่งเมื่อ'),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='flagged',
            field=models.JSONField(blank=True, default=list, verbose_name='ข้อที่ปักธง'),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='queue',
            field=models.JSONField(blank=True, default=list, verbose_name='ชุดคำถาม'),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='section',
            field=models.CharField(blank=True, choices=[('listening', '听力 ฟัง'), ('reading', '阅读 อ่าน'), ('writing', '书写 เขียน'), ('vocab', 'คำศัพท์ (ฝึกเอง ไม่ใช่พาร์ทในข้อสอบ)')], max_length=16, verbose_name='พาร์ทที่จำลอง'),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='เริ่มทำ'),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='time_limit_minutes',
            field=models.PositiveSmallIntegerField(default=45, verbose_name='เวลาที่ให้ (นาที)'),
        ),
    ]
