# Generated by Django 5.2.5 on 2026-08-27 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mockexam_answers_mockexam_auto_submitted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='เริ่ม')),
                ('studied_at', models.DateTimeField(blank=True, null=True, verbose_name='กดว่าจำเสร็จแล้วเมื่อ')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='จบ')),
                ('phase', models.CharField(choices=[('study', 'กำลังดูคำ'), ('test', 'กำลังทดสอบ')], default='study', max_length=8, verbose_name='อยู่ขั้นไหน')),
                ('mode', models.CharField(choices=[('meaning', 'เห็นตัวอักษร → เลือกความหมาย'), ('hanzi', 'เห็นความหมาย → เลือกตัวอักษร')], default='meaning', max_length=16, verbose_name='รูปแบบการถาม')),
                ('scope', models.JSONField(blank=True, default=dict, help_text='เช่น {"tier": "fresh", "window": 7, "level": 5} — เก็บไว้ให้ย้อนดูได้ว่าทบทวนอะไรไป', verbose_name='เงื่อนไขที่เลือก')),
                ('queue', models.JSONField(blank=True, default=list, verbose_name='คิวการ์ดที่ล็อกไว้')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ทำถึงข้อที่')),
                ('answered', models.PositiveSmallIntegerField(default=0, verbose_name='ตอบไปแล้ว')),
                ('correct', models.PositiveSmallIntegerField(default=0, verbose_name='ถูก')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to='core.learnerprofile', verbose_name='ผู้เรียน')),
            ],
            options={
                'verbose_name': 'ทบทวนอิสระ',
                'verbose_name_plural': 'ทบทวนอิสระ',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['learner', '-started_at'], name='core_review_learner_aa9ed2_idx')],
            },
        ),
    ]
