# Generated by Django 5.2.5 on 2026-08-31 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_reviewsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='วันที่')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เข้าครั้งแรกของวันเมื่อ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_days', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'วันที่เข้าระบบ',
                'verbose_name_plural': 'วันที่เข้าระบบ',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uniq_login_per_day')],
            },
        ),
    ]
