# Generated by Django 5.2.5 on 2026-08-31 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_loginday'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordOrderAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_correct', models.BooleanField(default=False, verbose_name='เรียงถูก')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_order_attempts', to='core.learnerprofile', verbose_name='ผู้เรียน')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_order_attempts', to='core.question', verbose_name='ข้อที่ทำ')),
            ],
            options={
                'verbose_name': 'ครั้งที่ฝึกเรียงคำ',
                'verbose_name_plural': 'ครั้งที่ฝึกเรียงคำ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['learner', '-created_at'], name='core_wordor_learner_49a231_idx')],
            },
        ),
    ]
