# Generated by Django 5.2.5 on 2026-08-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_wordorderattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanationnote',
            name='field_name',
            field=models.CharField(blank=True, default='', help_text='pinyin · pinyin_sandhi · meaning_th', max_length=32, verbose_name='แย้งเรื่องอะไร'),
        ),
        migrations.AddField(
            model_name='vocabitem',
            name='pinyin_sandhi',
            field=models.CharField(blank=True, help_text='ใส่ sandhi ของ 一/不 แล้ว — ว่างไว้ถ้าคำนี้ไม่มีการเปลี่ยนเสียง', max_length=96, verbose_name='พินอิน (รูปที่ออกเสียงจริง)'),
        ),
        migrations.AddField(
            model_name='vocabitem',
            name='pinyin_sandhi_source',
            field=models.CharField(blank=True, choices=[('official_list', 'ลิสต์คำศัพท์ทางการ HSK 2012'), ('human', 'ครูแก้เอง')], default='', max_length=24, verbose_name='ที่มาของรูปออกเสียง'),
        ),
        migrations.AddField(
            model_name='vocabitem',
            name='pinyin_sandhi_verified',
            field=models.BooleanField(default=False, verbose_name='ครูตรวจแล้ว'),
        ),
    ]
