# Generated by Django 5.2.5 on 2026-08-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_explanationnote_field_name_vocabitem_pinyin_sandhi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingfeedback',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0, verbose_name='โทเคนขาเข้า'),
        ),
        migrations.AddField(
            model_name='writingfeedback',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0, verbose_name='โทเคนขาออก'),
        ),
        migrations.AddField(
            model_name='writingsubmission',
            name='required_words',
            field=models.JSONField(blank=True, default=list, help_text='ข้อ 99 เท่านั้น — ข้อ 100 เว้นว่าง', verbose_name='คำที่ต้องใช้ให้ครบ'),
        ),
        migrations.AddField(
            model_name='writingsubmission',
            name='task_no',
            field=models.PositiveSmallIntegerField(default=99, verbose_name='ข้อที่'),
        ),
        migrations.AlterField(
            model_name='writingfeedback',
            name='scores',
            field=models.JSONField(default=dict, help_text='{"band": "mid", "typo_count": 1, "grammar_errors": 2, "char_count": 96, ...}', verbose_name='ผลตรวจแบบมีโครงสร้าง'),
        ),
        migrations.AlterField(
            model_name='writingfeedback',
            name='total_100',
            field=models.PositiveSmallIntegerField(default=0, help_text='ระบบประมาณจาก band — 汉办 ไม่เคยประกาศว่าแต่ละช่วงคือกี่คะแนน', verbose_name='คะแนนประมาณ (เต็ม 100)'),
        ),
    ]
