# Generated by Django 5.2.5 on 2026-08-31 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_writingfeedback_input_tokens_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='explanationnote',
            name='note_targets_exactly_one',
        ),
        migrations.AddField(
            model_name='explanationnote',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.writingsubmission', verbose_name='งานเขียนที่แย้ง'),
        ),
        migrations.AddConstraint(
            model_name='explanationnote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('question__isnull', False), ('submission__isnull', True), ('vocab__isnull', True)), models.Q(('question__isnull', True), ('submission__isnull', True), ('vocab__isnull', False)), models.Q(('question__isnull', True), ('submission__isnull', False), ('vocab__isnull', True)), _connector='OR'), name='note_targets_exactly_one'),
        ),
    ]
