# Generated by Django 5.2.5 on 2026-08-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_explanationnote_note_targets_exactly_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingsubmission',
            name='learner_note',
            field=models.CharField(blank=True, help_text='ผู้เรียนเขียนบอกได้ตอนกดขอตรวจ', max_length=300, verbose_name='อยากให้ดูตรงไหนเป็นพิเศษ'),
        ),
        migrations.AddField(
            model_name='writingsubmission',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ขอตรวจเมื่อ'),
        ),
        migrations.AddField(
            model_name='writingsubmission',
            name='review_state',
            field=models.CharField(choices=[('draft', 'ยังไม่ได้ขอตรวจ'), ('requested', 'รอเจ้าของระบบตรวจ'), ('answered', 'ตรวจแล้ว')], db_index=True, default='draft', max_length=12, verbose_name='สถานะการตรวจ'),
        ),
    ]
