# Generated by Django 5.2.5 on 2026-08-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_writingsubmission_learner_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='essay_consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ยินยอมให้ส่งงานเขียนไปตรวจเมื่อ'),
        ),
    ]
