# Generated by Django 5.2.5 on 2026-09-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_learnerprofile_essay_consent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_script',
            field=models.TextField(blank=True, help_text='ข้อฟังเท่านั้น — ว่างแปลว่ายังไม่มีเสียง ข้อนั้นตอบไม่ได้', verbose_name='บทที่อ่านออกเสียง'),
        ),
    ]
