# Generated by Django 5.2.5 on 2026-09-01 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_question_audio_script'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_correct', models.BooleanField(default=False, verbose_name='ตอบถูก')),
                ('plays', models.PositiveSmallIntegerField(default=1, help_text='ข้อสอบจริงได้ฟังครั้งเดียว — เกิน 1 แปลว่ายังไม่ทันความเร็วจริง', verbose_name='กดฟังกี่ครั้ง')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_attempts', to='core.learnerprofile', verbose_name='ผู้เรียน')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listening_attempts', to='core.question', verbose_name='ข้อที่ทำ')),
            ],
            options={
                'verbose_name': 'ครั้งที่ฝึกฟัง',
                'verbose_name_plural': 'ครั้งที่ฝึกฟัง',
                'ordering': ['-created_at'],
            },
        ),
    ]
