# Generated by Django 5.2.5 on 2026-09-01 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_listeningattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictationattempt',
            name='expected_text',
            field=models.TextField(blank=True, verbose_name='ประโยคที่ควรได้'),
        ),
        migrations.AddField(
            model_name='dictationattempt',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictations', to='core.question', verbose_name='ข้อที่บทมาจาก'),
        ),
        migrations.AlterField(
            model_name='dictationattempt',
            name='clip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictations', to='core.audioclip', verbose_name='ไฟล์เสียง'),
        ),
    ]
