# Generated by Django 5.2.5 on 2026-09-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_dictationattempt_expected_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_turns',
            field=models.JSONField(blank=True, default=list, help_text='[{"who": "f|m|q|n", "text": "…"}] — ว่างได้ ระบบจะกลับไปอ่านรวดเดียว', verbose_name='ช่วงพูดในบท'),
        ),
    ]
