# Generated by Django 5.2.5 on 2026-09-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_question_audio_turns'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='vocab_levels',
            field=models.JSONField(blank=True, default=list, help_text='เช่น [4, 5] — ว่างแปลว่าทุกระดับ', verbose_name='ระดับคำศัพท์ที่จะเรียนใหม่'),
        ),
    ]
